# Generated by Django 2.2 on 2021-04-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='mobile',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
