# Generated by Django 2.2 on 2021-04-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210425_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='merchant',
            new_name='user',
        ),
    ]
